CREATE CONSTRAINT project_slug IF NOT EXISTS
FOR (p:Project)
REQUIRE p.slug IS UNIQUE;

CREATE CONSTRAINT source_id IF NOT EXISTS
FOR (s:Source)
REQUIRE s.id IS UNIQUE;

CREATE CONSTRAINT source_span_id IF NOT EXISTS
FOR (s:SourceSpan)
REQUIRE s.id IS UNIQUE;

CREATE CONSTRAINT chunk_id IF NOT EXISTS
FOR (c:Chunk)
REQUIRE c.id IS UNIQUE;

CREATE CONSTRAINT assertion_id IF NOT EXISTS
FOR (a:Assertion)
REQUIRE a.id IS UNIQUE;

CREATE CONSTRAINT entity_id IF NOT EXISTS
FOR (e:Entity)
REQUIRE e.id IS UNIQUE;
